### ISSUE TITLE
improved integration between ictab and LOO

### ISSUE THREAD

**Issue by aschetti** [lnalborczyk/ESTER#4]
Hi Ladislas,
as anticipated via email (and in person :) ), I was wondering whether your **ictab** function could accept additional fields related to the model comparison function that you feed to it. For instance:

library(brms)
data(mtcars)
mod1 <- brm(mpg ~ cyl, mtcars)
mod2 <- brm(mpg ~ cyl + vs, mtcars)

library(ESTER)
ictab(LOO, mod1, mod2, **reloo=TRUE**) # emphasis mine

I hope this feature request is clear enough... and thanks again for your supercool package!

Thanks,
Antonio

**Comment by lnalborczyk** [comment]
Hi Antonio,

thanks for opening an issue. I am not sure how to attack this question as I already use the "three-dots strategy" in `ictab` to capture multiple models with NSE. A solution would be to ask the user to provide a list of models (instead of comma-separated models), and to reserve the three dots to extra arguments to be passed to the IC function (e.g., to `brms::LOO` or to `brms::WAIC`)... but I am not sure whether I like this solution either.

A temporary hack would consist in creating your own `LOO` function, with the desired parameters values.

For instance:

```
LOO_custom <- function(x) {
    
    brms::LOO(x, reloo = TRUE, k_threshold = 0.8)
    
}
```

And then using the `ictab` function with this new `LOO_custom` function. 

```
library(brms)
data(mtcars)
mod1 <- brm(mpg ~ cyl, mtcars)
mod2 <- brm(mpg ~ cyl + vs, mtcars)

library(ESTER)
ictab(LOO_custom, mod1, mod2)
```

This should work with the latest development version I just uploaded to Github.

Cheers,
Ladislas

**Comment by aschetti** [comment]
Hi Ladislas,
thanks for the hack, I'll try it tomorrow. I don't know if this might be a feasible solution, but perhaps you could let the ```ictab``` function simply compute the weighted ICs after they have been computed by the other functions (e.g., ```brms::LOO``` or ```brms::WAIC```). In other words, you just feed the output of these functions to ```ictab```, which will simply compute the weighted ICs. Does it make sense?

**Comment by lnalborczyk** [comment]
Additional arguments can now be passed to the `ictab` function but models should be passed as a **named** list (i.e., meaning the models should be given a name when creating the list).

For instance

```
library(ESTER)
library(brms)
data(mtcars)
mod1 <- lm(mpg ~ cyl, mtcars)
mod2 <- lm(mpg ~ cyl + vs, mtcars)
mods <- list(m1 = mod1, m2 = mod2)
ictab(mods, LOO, reloo = TRUE, k_threshold = 0.6, cores = 2)
```

See `?ictab` for more details.
